# Generated by Django 5.2.7 on 2025-10-20 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                (
                    "telefono",
                    models.CharField(
                        max_length=9,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número de teléfono debe tener exactamente 9 dígitos numéricos.",
                                regex="^\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contraseña", models.CharField(max_length=200)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[("EST", "Estudiante"), ("ADM", "Administrador")],
                        default="EST",
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
