# Generated by Django 5.2.7 on 2025-10-22 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuarios",
            options={"verbose_name": "usuario", "verbose_name_plural": "usuarios"},
        ),
    ]
