# Generated by Django 5.2.7 on 2025-10-22 03:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inscripcion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscripcion",
            options={
                "verbose_name": "inscripcion",
                "verbose_name_plural": "inscripciones",
            },
        ),
    ]
